// This file was generated by piqued.
// You can edit it if you want, but you'll probably be sad
// If you have some changes you want to make, check out the configuration options
// Or file a bug report on our definitely-extant github


export namespace PiquedHead {
    export const name = "_piqued_head";
    
    export type t = {
        "index_key": number;
        "head": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["index_key", Number],
            ["head", String],
        ] as const,
    };
}

export namespace PromptGroup {
    export const name = "prompt_group";
    
    export type t = {
        "id": string;
        "name": string;
        "description": string | null;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["id", String],
            ["name", String],
            ["description", String],
        ] as const,
    };
}

export namespace Prompt {
    export const name = "prompt";
    
    export type t = {
        "id": string;
        /** Every prompt belongs to exactly one group -- there are no standalone prompts. Entries only ever gain prompts by adding a whole group. */
        "group_id": string;
        /** Ordering of this prompt within its group. */
        "position": number;
        "text": string;
        "archived": boolean;
        "created_at": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["id", String],
            ["group_id", String],
            ["position", Number],
            ["text", String],
            ["archived", Boolean],
            ["created_at", Date],
        ] as const,
    };
}

export namespace Entry {
    export const name = "entry";
    
    export type t = {
        "id": string;
        /** A civil/wall-clock date, not an instant -- the client sends its local date and it is stored literally, with no timezone conversion. */
        "entry_date": Date;
        /** The main journaling text for this day, independent of any attached prompts. An entry with zero attached prompts is still fully journal-able via this field alone. */
        "body": string | null;
        "created_at": Date;
        /** Short label for the entry, editable independently of body. Always set by the application -- defaults to a formatted date when not explicitly provided at creation. */
        "name": string;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["id", String],
            ["entry_date", Date],
            ["body", String],
            ["created_at", Date],
            ["name", String],
        ] as const,
    };
}

export namespace Recording {
    export const name = "recording";
    
    export type t = {
        "id": string;
        "entry_id": string;
        "path": string;
        "mime_type": string;
        "duration_ms": number;
        "size_bytes": number;
        "created_at": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["id", String],
            ["entry_id", String],
            ["path", String],
            ["mime_type", String],
            ["duration_ms", Number],
            ["size_bytes", Number],
            ["created_at", Date],
        ] as const,
    };
}

export namespace PromptResponse {
    export const name = "prompt_response";
    
    export type t = {
        "id": string;
        "entry_id": string;
        /** A frozen snapshot of the prompt's wording at the time it was attached to this entry -- not a reference to the prompt row. Keeps past responses stable if a prompt's wording is edited later, and means deleting a prompt is never blocked by existing responses. */
        "prompt_text": string;
        /** NULL until answered -- attaching a group's prompts to an entry does not require responding to them immediately. */
        "response": string | null;
        "created_at": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["id", String],
            ["entry_id", String],
            ["prompt_text", String],
            ["response", String],
            ["created_at", Date],
        ] as const,
    };
}

export namespace Task {
    export const name = "task";
    
    export type t = {
        "id": string;
        "text": string;
        /** NULL = not done, else the day it was done. */
        "done_date": Date | null;
        "created_at": Date;
    };
    
    export const spec = {
        kind: "composite" as const,
        fields: () => [
            ["id", String],
            ["text", String],
            ["done_date", Date],
            ["created_at", Date],
        ] as const,
    };
}

